# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DVT Weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DVT Weather
pod 'SwipeableTabBarController'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SVProgressHUD'
pod 'RxRetroSwift'
pod 'Cleanse'
pod 'ProgressHUD'
pod 'Toast', '~> 4.0.0'
pod 'Alertift', '~> 4.1'

  target 'DVT WeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DVT WeatherUITests' do
    # Pods for testing
  end

end
